configured_endpoints: 483
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-643855f37c5857eda3b4d99aad29fdbc75b24b24a4fc8b4697d2bc7bd803b98d.yml
