// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'unified-data-library-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Unifieddatalibrary from 'unified-data-library';

export const metadata: Metadata = {
  resource: 'onorbitantenna',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/udl/onorbitantenna',
};

export const tool: Tool = {
  name: 'create_onorbitantenna',
  description:
    'Service operation to take a single OnorbitAntenna as a POST body and ingest into the database. An OnorbitAntenna is the association between on-orbit spacecraft antennas and a particular on-orbit spacecraft. An antenna type may be associated with many different on-orbit spacecraft. A specific role is required to perform this service operation. Please contact the UDL team for assistance.',
  inputSchema: {
    type: 'object',
    properties: {
      classificationMarking: {
        type: 'string',
        description: 'Classification marking of the data in IC/CAPCO Portion-marked format.',
      },
      dataMode: {
        type: 'string',
        description:
          'Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:\n\nREAL:&nbsp;Data collected or produced that pertains to real-world objects, events, and analysis.\n\nTEST:&nbsp;Specific datasets used to evaluate compliance with specifications and requirements, and for validating technical, functional, and performance characteristics.\n\nEXERCISE:&nbsp;Data pertaining to a government or military exercise. The data may include both real and simulated data.\n\nSIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world datasets.',
        enum: ['REAL', 'TEST', 'SIMULATED', 'EXERCISE'],
      },
      idAntenna: {
        type: 'string',
        description: 'ID of the antenna.',
      },
      idOnOrbit: {
        type: 'string',
        description: 'ID of the on-orbit object.',
      },
      source: {
        type: 'string',
        description: 'Source of the data.',
      },
      id: {
        type: 'string',
        description: 'Unique identifier of the record, auto-generated by the system.',
      },
      antenna: {
        $ref: '#/$defs/antenna_ingest',
      },
      origin: {
        type: 'string',
        description:
          'Originating system or organization which produced the data, if different from the source. The origin may be different than the source if the source was a mediating system which forwarded the data on behalf of the origin system. If null, the source may be assumed to be the origin.',
      },
    },
    required: ['classificationMarking', 'dataMode', 'idAntenna', 'idOnOrbit', 'source'],
    $defs: {
      antenna_ingest: {
        type: 'object',
        description:
          "Model representation of information on on-orbit/spacecraft communication antennas. A spacecraft may have multiple antennas and each antenna can have multiple 'details' records compiled by different sources.",
        properties: {
          dataMode: {
            type: 'string',
            description:
              'Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:\n\nREAL:&nbsp;Data collected or produced that pertains to real-world objects, events, and analysis.\n\nTEST:&nbsp;Specific datasets used to evaluate compliance with specifications and requirements, and for validating technical, functional, and performance characteristics.\n\nEXERCISE:&nbsp;Data pertaining to a government or military exercise. The data may include both real and simulated data.\n\nSIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world datasets.',
            enum: ['REAL', 'TEST', 'SIMULATED', 'EXERCISE'],
          },
          name: {
            type: 'string',
            description: 'Antenna name.',
          },
          source: {
            type: 'string',
            description: 'Source of the data.',
          },
          id: {
            type: 'string',
            description: 'Unique identifier of the record, auto-generated by the system.',
          },
          createdAt: {
            type: 'string',
            description: 'Time the row was created in the database, auto-populated by the system.',
            format: 'date-time',
          },
          createdBy: {
            type: 'string',
            description:
              'Application user who created the row in the database, auto-populated by the system.',
          },
          origin: {
            type: 'string',
            description:
              'Originating system or organization which produced the data, if different from the source. The origin may be different than the source if the source was a mediating system which forwarded the data on behalf of the origin system. If null, the source may be assumed to be the origin.',
          },
          origNetwork: {
            type: 'string',
            description:
              'The originating source network on which this record was created, auto-populated by the system.',
          },
        },
        required: ['dataMode', 'name', 'source'],
      },
    },
  },
  annotations: {},
};

export const handler = async (client: Unifieddatalibrary, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  const response = await client.onorbitantenna.create(body).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
