// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'unified-data-library-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Unifieddatalibrary from 'unified-data-library';

export const metadata: Metadata = {
  resource: 'transponder',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/udl/transponder',
};

export const tool: Tool = {
  name: 'create_transponder',
  description:
    'Service operation to take a single Transponder as a POST body and ingest into the database. A specific role is required to perform this service operation. Please contact the UDL team for assistance. A Comm payload may have multiple transponders and a transponder may have many channels.',
  inputSchema: {
    type: 'object',
    properties: {
      classificationMarking: {
        type: 'string',
        description: 'Classification marking of the data in IC/CAPCO Portion-marked format.',
      },
      dataMode: {
        type: 'string',
        description:
          'Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:\n\nREAL:&nbsp;Data collected or produced that pertains to real-world objects, events, and analysis.\n\nTEST:&nbsp;Specific datasets used to evaluate compliance with specifications and requirements, and for validating technical, functional, and performance characteristics.\n\nEXERCISE:&nbsp;Data pertaining to a government or military exercise. The data may include both real and simulated data.\n\nSIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world datasets.',
        enum: ['REAL', 'TEST', 'SIMULATED', 'EXERCISE'],
      },
      idComm: {
        type: 'string',
        description: 'ID of the parent Comm object for this transponder.',
      },
      source: {
        type: 'string',
        description: 'Source of the data.',
      },
      id: {
        type: 'string',
        description: 'Unique identifier of the record, auto-generated by the system.',
      },
      fec: {
        type: 'integer',
        description:
          'Forward error correction, e.g. 0=Auto, 1 = 1/2, 2 = 2/3, 3 = 3/4, 4 = 5/6, 5 = 7/8, 6 = 8/9, 7 = 3/5, 8 = 4/5, 9 = 9/10, 15 = None.',
      },
      format: {
        type: 'string',
        description: 'Format.',
      },
      modulation: {
        type: 'string',
        description: 'Transponder modulation, e.g. Auto, QPSK, 8PSK.',
      },
      name: {
        type: 'string',
        description: 'Optional name of the transponder.',
      },
      nid: {
        type: 'string',
        description: 'Optional external network id as provided data source.',
      },
      origin: {
        type: 'string',
        description:
          'Originating system or organization which produced the data, if different from the source. The origin may be different than the source if the source was a mediating system which forwarded the data on behalf of the origin system. If null, the source may be assumed to be the origin.',
      },
      symbolRate: {
        type: 'number',
        description:
          'Symbol rate is the number of symbol changes, waveform changes, or signaling events, across the transmission medium per time unit using a digitally modulated signal or a line code. Also measured in Hz.',
      },
      system: {
        type: 'string',
        description: 'Transponder system, e.g. DVB-S, DVB-S2.',
      },
      tid: {
        type: 'string',
        description: 'Optional external transponder id as provided data source.',
      },
      ttf: {
        type: 'number',
        description:
          'Transponder Translation Factor. This is the frequency difference between the uplink received by a satellite, and the downlink transmitted back. It varies satellite to satellite dependent on the mission.',
      },
    },
    required: ['classificationMarking', 'dataMode', 'idComm', 'source'],
  },
  annotations: {},
};

export const handler = async (client: Unifieddatalibrary, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  const response = await client.transponder.create(body).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
