// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'unified-data-library-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Unifieddatalibrary from 'unified-data-library';

export const metadata: Metadata = {
  resource: 'observations.passive_radar_observation',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/udl/passiveradarobservation/createBulk',
};

export const tool: Tool = {
  name: 'create_bulk_observations_passive_radar_observation',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nService operation intended for initial integration only, to take a list of PassiveRadarObservation records as a POST body and ingest into the database. This operation is not intended to be used for automated feeds into UDL. Data providers should contact the UDL team for specific role assignments and for instructions on setting up a permanent feed through an alternate mechanism.",
  inputSchema: {
    type: 'object',
    properties: {
      body: {
        type: 'array',
        items: {
          type: 'object',
          description:
            'Model representation of observation data for passive radar based sensor phenomenologies. Passive radar is a form of radar that instead of using a dedicated transmitter, as is the case for traditional radar, utilizes radio frequency (RF) energy already in the environment. With an abundance of existing energy available from geographically diverse sources, passive radar offers wide field of view coverage and long observation times. A passive radar system is comprised of separately located transmitter (for example, FM radio stations), a reference receiver, and a surveillance sensor. The transmitted signal illuminates multiple targets over a broad angular extent as well as providing a signal at the reference site. The reflected energy is received at the surveillance site for processing with the reference signal. The long observation durations that are possible with this technology enables an accurate orbit to be determined within a single pass.',
          properties: {
            classificationMarking: {
              type: 'string',
              description: 'Classification marking of the data in IC/CAPCO Portion-marked format.',
            },
            dataMode: {
              type: 'string',
              description:
                'Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:\n\nEXERCISE:&nbsp;Data pertaining to a government or military exercise. The data may include both real and simulated data.\n\nREAL:&nbsp;Data collected or produced that pertains to real-world objects, events, and analysis.\n\nSIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world datasets.\n\nTEST:&nbsp;Specific datasets used to evaluate compliance with specifications and requirements, and for validating technical, functional, and performance characteristics.',
              enum: ['REAL', 'TEST', 'SIMULATED', 'EXERCISE'],
            },
            obTime: {
              type: 'string',
              description: 'Ob detection time in ISO 8601 UTC with microsecond precision.',
              format: 'date-time',
            },
            source: {
              type: 'string',
              description: 'Source of the data.',
            },
            id: {
              type: 'string',
              description: 'Unique identifier of the record, auto-generated by the system.',
            },
            accel: {
              type: 'number',
              description: 'The target Acceleration measurement in kilometers/sec^2 for this observation.',
            },
            accelUnc: {
              type: 'number',
              description:
                'The target Acceleration uncertainty measurement in kilometers/sec^2 for this observation.',
            },
            alt: {
              type: 'number',
              description:
                'The target altitude relative to WGS-84 ellipsoid, in kilometers for this observation.',
            },
            azimuth: {
              type: 'number',
              description: 'Line of sight azimuth angle in degrees and topocentric frame.',
            },
            azimuthBias: {
              type: 'number',
              description: 'Sensor azimuth angle bias in degrees.',
            },
            azimuthRate: {
              type: 'number',
              description: 'Rate of change of the line of sight azimuth in degrees per second.',
            },
            azimuthUnc: {
              type: 'number',
              description:
                'One sigma uncertainty in the line of sight azimuth angle measurement, in degrees.',
            },
            bistaticRange: {
              type: 'number',
              description:
                'Target bistatic path distance in kilometers. This is the transmitter-to-target-to-surveillance site distance.',
            },
            bistaticRangeAccel: {
              type: 'number',
              description: 'Bistatic range acceleration in kilometers/sec^2.',
            },
            bistaticRangeAccelUnc: {
              type: 'number',
              description:
                'One sigma uncertainty in the bistatic range acceleration measurement, in kilometers/sec^2.',
            },
            bistaticRangeBias: {
              type: 'number',
              description: 'Sensor bistatic range bias in kilometers.',
            },
            bistaticRangeRate: {
              type: 'number',
              description: 'Rate of change of the bistatic path in kilometers/sec.',
            },
            bistaticRangeRateUnc: {
              type: 'number',
              description: 'One sigma uncertainty in rate of change of the bistatic path in kilometers/sec.',
            },
            bistaticRangeUnc: {
              type: 'number',
              description: 'One sigma uncertainty in bistatic range in kilometers.',
            },
            coning: {
              type: 'number',
              description: 'Coning angle in degrees.',
            },
            coningUnc: {
              type: 'number',
              description: 'One sigma uncertainty in the coning angle measurement, in degrees.',
            },
            createdAt: {
              type: 'string',
              description: 'Time the row was created in the database, auto-populated by the system.',
              format: 'date-time',
            },
            createdBy: {
              type: 'string',
              description:
                'Application user who created the row in the database, auto-populated by the system.',
            },
            declination: {
              type: 'number',
              description: 'Line of sight declination angle in degrees and J2000 coordinate frame.',
            },
            delay: {
              type: 'number',
              description:
                'The time difference, in seconds, between the signal collected at the surveillance site (after being reflected from the target) and the reference site (direct path line-of-sight signal).',
            },
            delayBias: {
              type: 'number',
              description: 'Delay bias in seconds.',
            },
            delayUnc: {
              type: 'number',
              description: 'One sigma uncertainty in the delay measurement, in seconds.',
            },
            descriptor: {
              type: 'string',
              description: 'Optional source-provided and searchable metadata or descriptor of the data.',
            },
            doppler: {
              type: 'number',
              description: 'Doppler measurement in hertz.',
            },
            dopplerUnc: {
              type: 'number',
              description: 'One sigma uncertainty in the Doppler measurement in hertz.',
            },
            elevation: {
              type: 'number',
              description: 'Line of sight elevation in degrees and topocentric frame.',
            },
            elevationBias: {
              type: 'number',
              description: 'Sensor elevation bias in degrees.',
            },
            elevationRate: {
              type: 'number',
              description: 'Rate of change of the line of sight elevation in degrees per second.',
            },
            elevationUnc: {
              type: 'number',
              description:
                'One sigma uncertainty in the line of sight elevation angle measurement, in degrees.',
            },
            extObservationId: {
              type: 'string',
              description: 'Optional external observation identifier provided by the source.',
            },
            idOnOrbit: {
              type: 'string',
              description:
                "Unique identifier of the target satellite on-orbit object. This ID can be used to obtain additional information on an OnOrbit object using the 'get by ID' operation (e.g. /udl/onorbit/{id}). For example, the OnOrbit with idOnOrbit = 25544 would be queried as /udl/onorbit/25544.",
            },
            idRFEmitter: {
              type: 'string',
              description:
                "Unique identifier of the transmitter. This ID can be used to obtain additional information on an RFEmitter using the 'get by ID' operation (e.g. /udl/rfemitter/{id}). For example, the RFEmitter with idRFEmitter = abc would be queried as /udl/rfemitter/abc.",
            },
            idSensor: {
              type: 'string',
              description:
                "Unique identifier of the reporting surveillance sensor. This ID can be used to obtain additional information on a sensor using the 'get by ID' operation (e.g. /udl/sensor/{id}). For example, the sensor with idSensor = abc would be queried as /udl/sensor/abc.",
            },
            idSensorRefReceiver: {
              type: 'string',
              description:
                "Unique identifier of the reference receiver sensor. This ID can be used to obtain additional information on a sensor using the 'get by ID' operation (e.g. /udl/sensor/{id}). For example, the sensor with idSensor = abc would be queried as /udl/sensor/abc.",
            },
            lat: {
              type: 'number',
              description:
                'WGS-84 target latitude sub-point at observation time (obTime), represented as -90 to 90 degrees (negative values south of equator).',
            },
            lon: {
              type: 'number',
              description:
                'WGS-84 target longitude sub-point at observation time (obTime), represented as -180 to 180 degrees (negative values west of Prime Meridian).',
            },
            obPosition: {
              type: 'string',
              description:
                'The position of this observation within a track (FENCE, FIRST, IN, LAST, SINGLE).  This identifier is optional and, if null, no assumption should be made regarding whether other observations may or may not exist to compose a track.',
            },
            origin: {
              type: 'string',
              description:
                'Originating system or organization which produced the data, if different from the source. The origin may be different than the source if the source was a mediating system which forwarded the data on behalf of the origin system. If null, the source may be assumed to be the origin.',
            },
            origNetwork: {
              type: 'string',
              description:
                'The originating source network on which this record was created, auto-populated by the system.',
            },
            origObjectId: {
              type: 'string',
              description:
                'Optional identifier provided by observation source to indicate the target onorbit object of this observation. This may be an internal identifier and not necessarily a valid satellite number.',
            },
            origSensorId: {
              type: 'string',
              description:
                'Optional identifier provided by observation source to indicate the sensor identifier which produced this observation. This may be an internal identifier and not necessarily a valid sensor ID.',
            },
            orthogonalRcs: {
              type: 'number',
              description: 'Radar cross section in meters squared for orthogonal polarization.',
            },
            orthogonalRcsUnc: {
              type: 'number',
              description:
                'One sigma uncertainty in orthogonal polarization Radar Cross Section, in meters^2.',
            },
            ra: {
              type: 'number',
              description: 'Line of sight right ascension in degrees and J2000 coordinate frame.',
            },
            rcs: {
              type: 'number',
              description: 'Radar cross section in meters squared for polarization principal.',
            },
            rcsUnc: {
              type: 'number',
              description:
                'One sigma uncertainty in principal polarization Radar Cross Section, in meters^2.',
            },
            satNo: {
              type: 'integer',
              description: 'Satellite/Catalog number of the target on-orbit object.',
            },
            snr: {
              type: 'number',
              description: 'Signal to noise ratio, in dB.',
            },
            sourceDL: {
              type: 'string',
              description:
                'The source data library from which this record was received. This could be a remote or tactical UDL or another data library. If null, the record should be assumed to have originated from the primary Enterprise UDL.',
            },
            tags: {
              type: 'array',
              description:
                'Optional array of provider/source specific tags for this data, where each element is no longer than 32 characters, used for implementing data owner conditional access controls to restrict access to the data. Should be left null by data providers unless conditional access controls are coordinated with the UDL team.',
              items: {
                type: 'string',
              },
            },
            taskId: {
              type: 'string',
              description:
                'Optional identifier to indicate the specific tasking which produced this observation.',
            },
            timingBias: {
              type: 'number',
              description: 'Sensor timing bias in seconds.',
            },
            tof: {
              type: 'number',
              description:
                'Time of flight (TOF) in seconds. This is the calculated propagation time from transmitter-to-target-to-surveillance site.',
            },
            tofBias: {
              type: 'number',
              description: 'The Time of Flight (TOF) bias in seconds.',
            },
            tofUnc: {
              type: 'number',
              description: 'One sigma uncertainty in time of flight in seconds.',
            },
            trackId: {
              type: 'string',
              description: 'Unique identifier of a track that represents a tracklet for this observation.',
            },
            transactionId: {
              type: 'string',
              description:
                'Optional identifier to track a commercial or marketplace transaction executed to produce this data.',
            },
            type: {
              type: 'string',
              description:
                'Read only enumeration specifying the type of observation (e.g. OPTICAL, RADAR, RF, etc).',
            },
            uct: {
              type: 'boolean',
              description:
                "Boolean indicating this observation is part of an uncorrelated track or was unable to be correlated to a known object. This flag should only be set to true by data providers after an attempt to correlate to an on-orbit object was made and failed. If unable to correlate, the 'origObjectId' field may be populated with an internal data provider specific identifier.",
            },
            xvel: {
              type: 'number',
              description: 'X velocity of target in kilometers/sec in J2000 coordinate frame.',
            },
            yvel: {
              type: 'number',
              description: 'Y velocity of target in kilometers/sec in J2000 coordinate frame.',
            },
            zvel: {
              type: 'number',
              description: 'Z velocity of target in kilometers/sec in J2000 coordinate frame.',
            },
          },
          required: ['classificationMarking', 'dataMode', 'obTime', 'source'],
        },
      },
    },
    required: ['body'],
  },
  annotations: {},
};

export const handler = async (client: Unifieddatalibrary, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  const response = await client.observations.passiveRadarObservation.createBulk(body).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
