// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'unified-data-library-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import Unifieddatalibrary from 'unified-data-library';

export const metadata: Metadata = {
  resource: 'gnss_observationset',
  operation: 'write',
  tags: [],
  httpMethod: 'post',
  httpPath: '/filedrop/udl-gnssobset',
  operationId: 'filedrop_udl_gnssobset_post_id',
};

export const tool: Tool = {
  name: 'unvalidated_publish_gnss_observationset',
  description:
    'Service operation to accept one or more GNSSObservationSet(s) and associated GNSS Observation(s) as a POST body and ingest into the database. This operation is intended to be used for automated feeds into UDL. A specific role is required to perform this service operation. Please contact the UDL team for assistance.\n',
  inputSchema: {
    type: 'object',
    properties: {
      body: {
        type: 'array',
        items: {
          type: 'object',
          description: 'Set of GNSSObservation data.',
          properties: {
            classificationMarking: {
              type: 'string',
              description: 'Classification marking of the data in IC/CAPCO Portion-marked format.',
            },
            dataMode: {
              type: 'string',
              description:
                'Indicator of whether the data is REAL, TEST, EXERCISE, or SIMULATED data:\n\nREAL:&nbsp;Data collected or produced that pertains to real-world objects, events, and analysis.\n\nTEST:&nbsp;Specific datasets used to evaluate compliance with specifications and requirements, and for validating technical, functional, and performance characteristics.\n\nEXERCISE:&nbsp;Data pertaining to a government or military exercise. The data may include both real and simulated data.\n\nSIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world datasets.',
              enum: ['REAL', 'TEST', 'SIMULATED', 'EXERCISE'],
            },
            source: {
              type: 'string',
              description: 'Source of the data.',
            },
            ts: {
              type: 'string',
              description:
                'Observation Time, in ISO8601 UTC format with microsecond precision.  This timestamp applies to all observations within the set.',
              format: 'date-time',
            },
            id: {
              type: 'string',
              description: 'Unique identifier of the record, auto-generated by the system.',
            },
            agcState: {
              type: 'integer',
              description: 'GNSS Automatic Gain Control State.',
            },
            alt: {
              type: 'number',
              description:
                'Spacecraft altitude at observation time (ts), expressed in kilometers above WGS-84 ellipsoid.',
            },
            boresight: {
              type: 'array',
              description:
                'unit vector of the outward facing direction of the receiver boresight in a body-fixed coordinate system.',
              items: {
                type: 'number',
              },
            },
            createdAt: {
              type: 'string',
              description: 'Time the row was created in the database, auto-populated by the system.',
              format: 'date-time',
            },
            createdBy: {
              type: 'string',
              description:
                'Application user who created the row in the database, auto-populated by the system.',
            },
            esId: {
              type: 'string',
              description:
                'Unique identifier of the parent Ephemeris Set, if this data is correlated with an Ephemeris.  If reporting for a spacecraft with multiple onboard GNSS receivers, this ID may be associated with multiple GNSS Observation records if each receiver is synced to the ephemeris points.',
            },
            eventId: {
              type: 'string',
              description:
                'Optional source-provided identifier for this collection event. This field can be used to associate records related to the same event.',
            },
            gDop: {
              type: 'number',
              description: 'Geometric Dilution of Precision.',
            },
            gnssObservationList: {
              type: 'array',
              description: 'GNSSObservations associated with this GNSSObservationSet.',
              items: {
                type: 'object',
                description:
                  'Information for Global Navigation Satellite Systems (GNSS) Observations collected from GNSS receivers, including the specific GNSS sat from which each signal was received, and the observation codes of each observation in the record. Each GNSS Observation is associated with a GNSS Observation Set record containing data which applies to all observations in the set, including observation time, receiver location, and Dilution of Precision (DOP) values. Users can Reference RINEX 3+ documentation for further information concerning many of the standards and conventions for GNSS observations.',
                properties: {
                  agcState: {
                    type: 'integer',
                    description: 'GNSS Automatic Gain Control State.',
                  },
                  gnssSatId: {
                    type: 'string',
                    description:
                      'RINEX 3+ compliant GNSS System and Satellite Identifier (represented as SNN, where S is the system code, and NN is the satellite identifier) associated with this observation:\n\nG - GPS (NN = PRN)\n\nR - GLONASS (NN = Slot Number)\n\nS - SBAS Payload (NN = PRN-100)\n\nE - Galileo (NN = PRN)\n\nC - BeiDou (NN = PRN)\n\nJ - QZSS (NN = PRN - 1923)\n\nI - IRNSS (NN = PRN)',
                  },
                  ob: {
                    type: 'array',
                    description:
                      'Array of observation(s).  The ob array must be the same length as the obsCodeSet.  Pseudorange (C) is expressed meters, carrier phase (L) in cycles,  doppler (D) in Hz where + values indicate approaching sats, and signal strength C/No (S) in dB-Hz.',
                    items: {
                      type: 'number',
                    },
                  },
                  obsCodeSet: {
                    type: 'array',
                    description:
                      'The observation code set that applies to this observation record.  Reference RINEX 3+ for further information concerning observation code set conventions.',
                    items: {
                      type: 'string',
                    },
                  },
                  trackingStatus: {
                    type: 'integer',
                    description:
                      'Status of the GNSS receiver signal. Status options are 0, 1 or 2 (0 being the best).',
                  },
                },
              },
            },
            hDop: {
              type: 'number',
              description: 'Horizontal Dilution of Precision.',
            },
            idOnOrbit: {
              type: 'string',
              description: 'Unique identifier of the primary satellite on-orbit object.',
            },
            lat: {
              type: 'number',
              description:
                'WGS-84 spacecraft latitude sub-point at observation time (ts), represented as -90 to 90 degrees (negative values south of equator).',
            },
            lon: {
              type: 'number',
              description:
                'WGS-84 spacecraft longitude sub-point at observation time (ts), represented as -180 to 180 degrees (negative values west of Prime Meridian).',
            },
            markerType: {
              type: 'string',
              description:
                'The marker type of the observing receiver (AIRBORNE, ANIMAL, BALLISTIC, FIXED BUOY, FLOATING BUOY, FLOATING ICE, GEODETIC, GLACIER, GROUNDCRAFT, HUMAN, NON GEODETIC, NON PHYSICAL, SPACEBORNE, WATERCRAFT).  Reference RINEX 3+ for further information concerning marker types.',
            },
            navigationStatus: {
              type: 'string',
              description:
                'The current navigation status as defined by the data source. In general the navigation status specifies whether the signal is normal, degraded, or unavailable. For status value definitions please reach out to data source provider.',
            },
            obsCodes: {
              type: 'array',
              description:
                'Array of the strings containing the individual observation code sets that are contained within this GNSS Observation set.  Each string is a three-character representation of the measurement type, the channel, and the coding, in compliance with the RINEX 3+ standard (Pseudorange (C), Carrier Phase (L), Doppler (D), Signal Strength C/No (S), or Channel Number (X)).  See the GNSS Observation ob field for the units of measure associated with each observation type.',
              items: {
                type: 'string',
              },
            },
            origin: {
              type: 'string',
              description:
                'Originating system or organization which produced the data, if different from the source. The origin may be different than the source if the source was a mediating system which forwarded the data on behalf of the origin system. If null, the source may be assumed to be the origin.',
            },
            origNetwork: {
              type: 'string',
              description:
                'The originating source network on which this record was created, auto-populated by the system.',
            },
            origObjectId: {
              type: 'string',
              description:
                'Optional identifier provided by ephemeris source to indicate the target object of this ephemeris. This may be an internal identifier and not necessarily map to a valid satellite number.',
            },
            outage: {
              type: 'integer',
              description: 'Time, in seconds, that the receiver has been unable to compute a GNSS fix.',
            },
            pDop: {
              type: 'number',
              description: 'Position Dilution of Precision.',
            },
            quat: {
              type: 'array',
              description:
                "The quaternion describing the rotation of the body-fixed frame used for this system into the local geodetic frame, at observation time (ts). The array element order convention is scalar component first, followed by the three vector components. For a vector u in the body-fixed frame, the corresponding vector u' in the geodetic frame should satisfy u' = quq*, where q is this quaternion.",
              items: {
                type: 'number',
              },
            },
            receiver: {
              type: 'string',
              description:
                'The number or ID of the GNSS receiver associated with this data.  Each GNSS Observation Set is associated with only one receiver.  If reporting for multiple receivers a separate set should be generated for each.  A null value is assumed to indicate that only one receiver is present, or reported.',
            },
            satNo: {
              type: 'integer',
              description: 'Satellite/catalog number of the target on-orbit object.',
            },
            satPosition: {
              type: 'array',
              description:
                'Three element array, expressing the ECI J2K spacecraft position components, in kilometers, at observation time (ts). The array element order is [x, y, z].',
              items: {
                type: 'number',
              },
            },
            satVelocity: {
              type: 'array',
              description:
                'Three element array, expressing the ECI J2K spacecraft velocity components, in km/second, at observation time (ts).  The array element order is [xvel, yvel, zvel].',
              items: {
                type: 'number',
              },
            },
            srcIds: {
              type: 'array',
              description:
                "Array of UUIDs of the UDL data records that are related to this GNSS Observation Set. See the associated 'srcTyps' array for the specific types of data, positionally corresponding to the UUIDs in this array. The 'srcTyps' and 'srcIds' arrays must match in size. See the corresponding srcTyps array element for the data type of the UUID and use the appropriate API operation to retrieve that object (e.g. /udl/statevector/{uuid}).",
              items: {
                type: 'string',
              },
            },
            srcTyps: {
              type: 'array',
              description:
                "Array of UDL record types (AIS, CONJUNCTION, DOA, ELSET, EO, ESID, GROUNDIMAGE, POI, MANEUVER, MTI, NOTIFICATION, RADAR, RF, SIGACT, SKYIMAGE, SV, TRACK) that are related to this GNSS Observation Set. See the associated 'srcIds' array for the record UUIDs, positionally corresponding to the record types in this array. The 'srcTyps' and 'srcIds' arrays must match in size.",
              items: {
                type: 'string',
              },
            },
            tags: {
              type: 'array',
              description:
                'Optional array of provider/source specific tags for this data, where each element is no longer than 32 characters, used for implementing data owner conditional access controls to restrict access to the data. Should be left null by data providers unless conditional access controls are coordinated with the UDL team.',
              items: {
                type: 'string',
              },
            },
            tDop: {
              type: 'number',
              description: 'Time Dilution of Precision.',
            },
            trackingStatus: {
              type: 'integer',
              description:
                'Status of the GNSS receiver signal. Status options are 0, 1 or 2 (0 being the best).',
            },
            transactionId: {
              type: 'string',
              description:
                'Optional identifier to track a commercial or marketplace transaction executed to produce this data.',
            },
            vDop: {
              type: 'number',
              description: 'Vertical Dilution of Precision.',
            },
          },
          required: ['classificationMarking', 'dataMode', 'source', 'ts'],
        },
      },
    },
    required: ['body'],
  },
  annotations: {},
};

export const handler = async (client: Unifieddatalibrary, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  const response = await client.gnssObservationset.unvalidatedPublish(body).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
