// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import Unifieddatalibrary from 'unifieddatalibrary';
import { Response } from 'node-fetch';

const client = new Unifieddatalibrary({
  username: 'My Username',
  password: 'My Password',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource udlSensorplan', () => {
  test('create: only required params', async () => {
    const responsePromise = client.udlSensorplan.create([
      {
        classificationMarking: 'classificationMarking',
        dataMode: 'dataMode',
        recType: 'recType',
        source: 'source',
        startTime: '2019-12-27T18:11:19.117Z',
        type: 'type',
      },
    ]);
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('create: required and optional params', async () => {
    const response = await client.udlSensorplan.create([
      {
        classificationMarking: 'classificationMarking',
        dataMode: 'dataMode',
        recType: 'recType',
        source: 'source',
        startTime: '2019-12-27T18:11:19.117Z',
        type: 'type',
        id: 'id',
        collectRequests: [
          {
            classificationMarking: 'classificationMarking',
            dataMode: 'dataMode',
            source: 'source',
            startTime: '2019-12-27T18:11:19.117Z',
            type: 'type',
            id: 'id',
            alt: 0,
            argOfPerigee: 0,
            az: 0,
            createdAt: '2019-12-27T18:11:19.117Z',
            createdBy: 'createdBy',
            customer: 'customer',
            dec: 0,
            duration: 0,
            dwellId: 'dwellId',
            eccentricity: 0,
            el: 0,
            elset: {
              classificationMarking: 'classificationMarking',
              dataMode: 'dataMode',
              epoch: '2019-12-27T18:11:19.117Z',
              source: 'source',
              agom: 0,
              algorithm: 'algorithm',
              apogee: 0,
              argOfPerigee: 0,
              ballisticCoeff: 0,
              bStar: 0,
              createdAt: '2019-12-27T18:11:19.117Z',
              createdBy: 'createdBy',
              descriptor: 'descriptor',
              eccentricity: 0,
              ephemType: 0,
              idElset: 'idElset',
              idOnOrbit: 'idOnOrbit',
              idOrbitDetermination: 'idOrbitDetermination',
              inclination: 0,
              line1: 'line1',
              line2: 'line2',
              meanAnomaly: 0,
              meanMotion: 0,
              meanMotionDDot: 0,
              meanMotionDot: 0,
              origin: 'origin',
              origNetwork: 'origNetwork',
              origObjectId: 'origObjectId',
              perigee: 0,
              period: 0,
              raan: 0,
              rawFileURI: 'rawFileURI',
              revNo: 0,
              satNo: 0,
              semiMajorAxis: 0,
              sourcedData: ['string'],
              sourcedDataTypes: ['string'],
              sourceDL: 'sourceDL',
              tags: ['string'],
              transactionId: 'transactionId',
              uct: true,
            },
            endTime: '2019-12-27T18:11:19.117Z',
            epoch: '2019-12-27T18:11:19.117Z',
            esId: 'esId',
            extentAz: 0,
            extentEl: 0,
            extentRange: 0,
            externalId: 'externalId',
            frameRate: 0,
            freq: 0,
            freqMax: 0,
            freqMin: 0,
            idElset: 'idElset',
            idManifold: 'idManifold',
            idOnOrbit: 'idOnOrbit',
            idParentReq: 'idParentReq',
            idPlan: 'idPlan',
            idSensor: 'idSensor',
            idStateVector: 'idStateVector',
            inclination: 0,
            integrationTime: 0,
            iron: 0,
            irradiance: 0,
            lat: 0,
            lon: 0,
            msgCreateDate: '2019-12-27T18:11:19.117Z',
            msgType: 'msgType',
            notes: 'notes',
            numFrames: 0,
            numObs: 0,
            numTracks: 0,
            obType: 'obType',
            orbitRegime: 'orbitRegime',
            orientAngle: 0,
            origin: 'origin',
            origNetwork: 'origNetwork',
            origObjectId: 'origObjectId',
            origSensorId: 'origSensorId',
            planIndex: 0,
            polarization: 'polarization',
            priority: 'priority',
            ra: 0,
            raan: 0,
            range: 0,
            rcs: 0,
            rcsMax: 0,
            rcsMin: 0,
            reflectance: 0,
            satNo: 0,
            scenario: 'scenario',
            semiMajorAxis: 0,
            spectralModel: 'spectralModel',
            srchInc: 0,
            srchPattern: 'srchPattern',
            stateVector: {
              classificationMarking: 'classificationMarking',
              dataMode: 'dataMode',
              epoch: '2019-12-27T18:11:19.117Z',
              source: 'source',
              actualODSpan: 0,
              algorithm: 'algorithm',
              alt1ReferenceFrame: 'alt1ReferenceFrame',
              alt2ReferenceFrame: 'alt2ReferenceFrame',
              area: 0,
              bDot: 0,
              cmOffset: 0,
              cov: [0],
              covMethod: 'covMethod',
              covReferenceFrame: 'covReferenceFrame',
              createdAt: '2019-12-27T18:11:19.117Z',
              createdBy: 'createdBy',
              descriptor: 'descriptor',
              dragArea: 0,
              dragCoeff: 0,
              dragModel: 'dragModel',
              edr: 0,
              eqCov: [0],
              errorControl: 0,
              fixedStep: true,
              geopotentialModel: 'geopotentialModel',
              iau1980Terms: 0,
              idOnOrbit: 'idOnOrbit',
              idOrbitDetermination: 'idOrbitDetermination',
              idStateVector: 'idStateVector',
              integratorMode: 'integratorMode',
              inTrackThrust: true,
              lastObEnd: '2019-12-27T18:11:19.117Z',
              lastObStart: '2019-12-27T18:11:19.117Z',
              leapSecondTime: '2019-12-27T18:11:19.117Z',
              lunarSolar: true,
              mass: 0,
              obsAvailable: 0,
              obsUsed: 0,
              origin: 'origin',
              origNetwork: 'origNetwork',
              origObjectId: 'origObjectId',
              partials: 'partials',
              pedigree: 'pedigree',
              polarMotionX: 0,
              polarMotionY: 0,
              posUnc: 0,
              rawFileURI: 'rawFileURI',
              recODSpan: 0,
              referenceFrame: 'referenceFrame',
              residualsAcc: 0,
              revNo: 0,
              rms: 0,
              satNo: 0,
              sigmaPosUVW: [0],
              sigmaVelUVW: [0],
              solarFluxAPAvg: 0,
              solarFluxF10: 0,
              solarFluxF10Avg: 0,
              solarRadPress: true,
              solarRadPressCoeff: 0,
              solidEarthTides: true,
              sourcedData: ['string'],
              sourcedDataTypes: ['string'],
              sourceDL: 'sourceDL',
              srpArea: 0,
              stepMode: 'stepMode',
              stepSize: 0,
              stepSizeSelection: 'stepSizeSelection',
              tags: ['string'],
              taiUtc: 0,
              thrustAccel: 0,
              tracksAvail: 0,
              tracksUsed: 0,
              transactionId: 'transactionId',
              uct: true,
              ut1Rate: 0,
              ut1Utc: 0,
              velUnc: 0,
              xaccel: 0,
              xpos: 0,
              xposAlt1: 0,
              xposAlt2: 0,
              xvel: 0,
              xvelAlt1: 0,
              xvelAlt2: 0,
              yaccel: 0,
              ypos: 0,
              yposAlt1: 0,
              yposAlt2: 0,
              yvel: 0,
              yvelAlt1: 0,
              yvelAlt2: 0,
              zaccel: 0,
              zpos: 0,
              zposAlt1: 0,
              zposAlt2: 0,
              zvel: 0,
              zvelAlt1: 0,
              zvelAlt2: 0,
            },
            stopAlt: 0,
            stopLat: 0,
            stopLon: 0,
            suffix: 'suffix',
            tags: ['string'],
            targetSize: 0,
            taskCategory: 0,
            taskGroup: 'taskGroup',
            taskId: 'taskId',
            trueAnomoly: 0,
            uctFollowUp: true,
            visMag: 0,
            visMagMax: 0,
            visMagMin: 0,
            xAngle: 0,
            yAngle: 0,
          },
        ],
        createdAt: '2019-12-27T18:11:19.117Z',
        createdBy: 'createdBy',
        customer: 'customer',
        endTime: '2019-12-27T18:11:19.117Z',
        idSensor: 'idSensor',
        name: 'name',
        origin: 'origin',
        origNetwork: 'origNetwork',
        origSensorId: 'origSensorId',
        purpose: 'purpose',
        reqTotal: 0,
        senNetwork: 'senNetwork',
        status: 'status',
        tags: ['string'],
      },
    ]);
  });
});
