// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import Unifieddatalibrary from 'unifieddatalibrary';
import { Response } from 'node-fetch';

const client = new Unifieddatalibrary({
  username: 'My Username',
  password: 'My Password',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource udlSoiobservationset', () => {
  test('create: only required params', async () => {
    const responsePromise = client.udlSoiobservationset.create([
      {
        classificationMarking: 'classificationMarking',
        dataMode: 'dataMode',
        numObs: 0,
        source: 'source',
        startTime: '2019-12-27T18:11:19.117Z',
        type: 'type',
      },
    ]);
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('create: required and optional params', async () => {
    const response = await client.udlSoiobservationset.create([
      {
        classificationMarking: 'classificationMarking',
        dataMode: 'dataMode',
        numObs: 0,
        source: 'source',
        startTime: '2019-12-27T18:11:19.117Z',
        type: 'type',
        id: 'id',
        binningHoriz: 0,
        binningVert: 0,
        brightnessVarianceChangeDetected: true,
        calibrations: [
          {
            calBgIntensity: 0,
            calExtinctionCoeff: 0,
            calExtinctionCoeffMaxUnc: 0,
            calExtinctionCoeffUnc: 0,
            calNumCorrelatedStars: 0,
            calNumDetectedStars: 0,
            calSkyBg: 0,
            calSpectralFilterSolarMag: 0,
            calTime: '2019-12-27T18:11:19.117Z',
            calType: 'calType',
            calZeroPoint: 0,
          },
        ],
        calibrationType: 'calibrationType',
        changeConf: 'changeConf',
        changeDetected: true,
        collectionDensityConf: 'collectionDensityConf',
        collectionId: 'collectionId',
        collectionMode: 'collectionMode',
        corrQuality: 0,
        createdAt: '2019-12-27T18:11:19.117Z',
        createdBy: 'createdBy',
        endTime: '2019-12-27T18:11:19.117Z',
        gain: 0,
        idElset: 'idElset',
        idOnOrbit: 'idOnOrbit',
        idSensor: 'idSensor',
        losDeclinationEnd: 0,
        losDeclinationStart: 0,
        msgCreateDate: '2019-12-27T18:11:19.117Z',
        numSpectralFilters: 0,
        opticalSOIObservationList: [
          {
            obStartTime: '2019-12-27T18:11:19.117Z',
            currentSpectralFilterNum: 0,
            declinations: [0],
            expDuration: 0,
            extinctionCoeffs: [0],
            extinctionCoeffsUnc: [0],
            intensities: [0],
            intensityTimes: ['2019-12-27T18:11:19.117Z'],
            localSkyBgs: [0],
            localSkyBgsUnc: [0],
            numCorrelatedStars: [0],
            numDetectedStars: [0],
            percentSats: [0],
            raRates: [0],
            ras: [0],
            skyBgs: [0],
            zeroPoints: [0],
          },
        ],
        origin: 'origin',
        origNetwork: 'origNetwork',
        origObjectId: 'origObjectId',
        origSensorId: 'origSensorId',
        percentSatThreshold: 0,
        periodicityChangeDetected: true,
        periodicityDetectionConf: 'periodicityDetectionConf',
        periodicitySamplingConf: 'periodicitySamplingConf',
        pixelArrayHeight: 0,
        pixelArrayWidth: 0,
        pixelMax: 0,
        pixelMin: 0,
        pointingAngleAzEnd: 0,
        pointingAngleAzStart: 0,
        pointingAngleElEnd: 0,
        pointingAngleElStart: 0,
        polarAngleEnd: 0,
        polarAngleStart: 0,
        radarSOIObservationList: [
          {
            obStartTime: '2019-12-27T18:11:19.117Z',
            aspectAngles: [0],
            azimuthBiases: [0],
            azimuthRates: [0],
            azimuths: [0],
            beta: 0,
            centerFrequency: 0,
            crossRangeRes: [0],
            deltaTimes: [0],
            doppler2XRs: [0],
            elevationBiases: [0],
            elevationRates: [0],
            elevations: [0],
            idAttitudeSet: 'idAttitudeSet',
            idStateVector: 'idStateVector',
            integrationAngles: [0],
            kappa: 0,
            peakAmplitudes: [0],
            polarizations: ['string'],
            projAngVels: [0],
            pulseBandwidth: 0,
            rangeAccels: [0],
            rangeBiases: [0],
            rangeRates: [0],
            ranges: [0],
            rcsErrorEsts: [0],
            rcsValues: [0],
            rspaces: [0],
            spectralWidths: [0],
            tovs: ['2019-12-27T18:11:19.117Z'],
            xaccel: [0],
            xpos: [0],
            xspaces: [0],
            xvel: [0],
            yaccel: [0],
            ypos: [0],
            yvel: [0],
            zaccel: [0],
            zpos: [0],
            zvel: [0],
          },
        ],
        referenceFrame: 'referenceFrame',
        satelliteName: 'satelliteName',
        satNo: 0,
        senalt: 0,
        senlat: 0,
        senlon: 0,
        senReferenceFrame: 'senReferenceFrame',
        sensorAsId: 'sensorAsId',
        senvelx: 0,
        senvely: 0,
        senvelz: 0,
        senx: 0,
        seny: 0,
        senz: 0,
        softwareVersion: 'softwareVersion',
        solarMag: 0,
        solarPhaseAngleBrightnessChangeDetected: true,
        sourceDL: 'sourceDL',
        spectralFilters: ['string'],
        starCatName: 'starCatName',
        tags: ['string'],
        transactionId: 'transactionId',
        uct: true,
        validCalibrations: 'validCalibrations',
      },
    ]);
  });
});
