// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import Unifieddatalibrary from 'unifieddatalibrary';
import { Response } from 'node-fetch';

const client = new Unifieddatalibrary({
  username: 'My Username',
  password: 'My Password',
  baseURL: process.env['TEST_API_BASE_URL'] ?? 'http://127.0.0.1:4010',
});

describe('resource udlSkyimagery', () => {
  test('create: only required params', async () => {
    const responsePromise = client.udlSkyimagery.create({
      classificationMarking: 'classificationMarking',
      dataMode: 'dataMode',
      expStartTime: '2019-12-27T18:11:19.117Z',
      imageType: 'imageType',
      source: 'source',
    });
    const rawResponse = await responsePromise.asResponse();
    expect(rawResponse).toBeInstanceOf(Response);
    const response = await responsePromise;
    expect(response).not.toBeInstanceOf(Response);
    const dataAndResponse = await responsePromise.withResponse();
    expect(dataAndResponse.data).toBe(response);
    expect(dataAndResponse.response).toBe(rawResponse);
  });

  test('create: required and optional params', async () => {
    const response = await client.udlSkyimagery.create({
      classificationMarking: 'classificationMarking',
      dataMode: 'dataMode',
      expStartTime: '2019-12-27T18:11:19.117Z',
      imageType: 'imageType',
      source: 'source',
      id: 'id',
      annotationKey: 'annotationKey',
      calibrationKey: 'calibrationKey',
      checksumValue: 'checksumValue',
      createdAt: '2019-12-27T18:11:19.117Z',
      createdBy: 'createdBy',
      description: 'description',
      eoObservations: [
        {
          classificationMarking: 'classificationMarking',
          dataMode: 'dataMode',
          obTime: '2019-12-27T18:11:19.117Z',
          source: 'source',
          id: 'id',
          azimuth: 0,
          azimuthBias: 0,
          azimuthRate: 0,
          azimuthUnc: 0,
          bgIntensity: 0,
          collectMethod: 'collectMethod',
          corrQuality: 0,
          createdAt: '2019-12-27T18:11:19.117Z',
          createdBy: 'createdBy',
          declination: 0,
          declinationBias: 0,
          declinationRate: 0,
          declinationUnc: 0,
          descriptor: 'descriptor',
          elevation: 0,
          elevationBias: 0,
          elevationRate: 0,
          elevationUnc: 0,
          eoobservationDetails: {
            acalCrPixX: 0,
            acalCrPixY: 0,
            acalCrValX: 0,
            acalCrValY: 0,
            acalNumStars: 0,
            backgroundSignal: 0,
            backgroundSignalUnc: 0,
            binningHoriz: 0,
            binningVert: 0,
            ccdObjPosX: 0,
            ccdObjPosY: 0,
            ccdObjWidth: 0,
            ccdTemp: 0,
            centroidColumn: 0,
            centroidRow: 0,
            classificationMarking: 'classificationMarking',
            colorCoeffs: [0],
            columnVariance: 0,
            createdAt: '2019-12-27T18:11:19.117Z',
            createdBy: 'createdBy',
            currentNeutralDensityFilterNum: 0,
            currentSpectralFilterNum: 0,
            dataMode: 'dataMode',
            declinationCov: 0,
            distFromStreakCenter: [0],
            does: 0,
            extinctionCoeffs: [0],
            extinctionCoeffsUnc: [0],
            gain: 0,
            idEOObservation: 'idEOObservation',
            ifov: 0,
            magInstrumental: 0,
            magInstrumentalUnc: 0,
            neutralDensityFilterNames: ['string'],
            neutralDensityFilterTransmissions: [0],
            neutralDensityFilterTransmissionsUnc: [0],
            numCatalogStars: 0,
            numCorrelatedStars: 0,
            numDetectedStars: 0,
            numNeutralDensityFilters: 0,
            numSpectralFilters: 0,
            objSunRange: 0,
            obTime: '2019-12-27T18:11:19.117Z',
            opticalCrossSection: 0,
            opticalCrossSectionUnc: 0,
            pcalNumStars: 0,
            peakApertureCount: 0,
            peakBackgroundCount: 0,
            phaseAngBisect: 0,
            pixelArrayHeight: 0,
            pixelArrayWidth: 0,
            pixelMax: 0,
            pixelMin: 0,
            predictedAzimuth: 0,
            predictedDeclination: 0,
            predictedDeclinationUnc: 0,
            predictedElevation: 0,
            predictedRa: 0,
            predictedRaUnc: 0,
            raCov: 0,
            raDeclinationCov: 0,
            rowColCov: 0,
            rowVariance: 0,
            snrEst: 0,
            solarDiskFrac: 0,
            source: 'source',
            spectralFilters: ['string'],
            spectralFilterSolarMag: [0],
            spectralZMFL: [0],
            sunAzimuth: 0,
            sunElevation: 0,
            sunStatePosX: 0,
            sunStatePosY: 0,
            sunStatePosZ: 0,
            sunStateVelX: 0,
            sunStateVelY: 0,
            sunStateVelZ: 0,
            surfBrightness: [0],
            surfBrightnessUnc: [0],
            timesUnc: 0,
            toes: 0,
            zeroPoints: [0],
            zeroPointsUnc: [0],
          },
          expDuration: 0,
          fovCount: 0,
          geoalt: 0,
          geolat: 0,
          geolon: 0,
          georange: 0,
          idOnOrbit: 'idOnOrbit',
          idSensor: 'idSensor',
          idSkyImagery: 'idSkyImagery',
          intensity: 0,
          losUnc: 0,
          losx: 0,
          losxvel: 0,
          losy: 0,
          losyvel: 0,
          losz: 0,
          loszvel: 0,
          mag: 0,
          magNormRange: 0,
          magUnc: 0,
          netObjSig: 0,
          netObjSigUnc: 0,
          obPosition: 'obPosition',
          origin: 'origin',
          origNetwork: 'origNetwork',
          origObjectId: 'origObjectId',
          origSensorId: 'origSensorId',
          penumbra: true,
          primaryExtinction: 0,
          primaryExtinctionUnc: 0,
          ra: 0,
          raBias: 0,
          range: 0,
          rangeBias: 0,
          rangeRate: 0,
          rangeRateUnc: 0,
          rangeUnc: 0,
          raRate: 0,
          raUnc: 0,
          rawFileURI: 'rawFileURI',
          referenceFrame: 'referenceFrame',
          satNo: 0,
          senalt: 0,
          senlat: 0,
          senlon: 0,
          senQuat: [0],
          senReferenceFrame: 'senReferenceFrame',
          senvelx: 0,
          senvely: 0,
          senvelz: 0,
          senx: 0,
          seny: 0,
          senz: 0,
          shutterDelay: 0,
          skyBkgrnd: 0,
          solarDecAngle: 0,
          solarEqPhaseAngle: 0,
          solarPhaseAngle: 0,
          sourceDL: 'sourceDL',
          tags: ['string'],
          taskId: 'taskId',
          timingBias: 0,
          trackId: 'trackId',
          transactionId: 'transactionId',
          type: 'type',
          uct: true,
          umbra: true,
          zeroptd: 0,
          zeroPtdUnc: 0,
        },
      ],
      expEndTime: '2019-12-27T18:11:19.117Z',
      filename: 'filename',
      filesize: 0,
      frameFOVHeight: 0,
      frameFOVWidth: 0,
      frameHeightPixels: 0,
      frameWidthPixels: 0,
      idAttitudeSet: 'idAttitudeSet',
      idOnOrbit: 'idOnOrbit',
      idSensor: 'idSensor',
      idSOISet: 'idSOISet',
      imageSetId: 'imageSetId',
      imageSetLength: 0,
      imageSourceInfo: 'imageSourceInfo',
      origin: 'origin',
      origNetwork: 'origNetwork',
      origObjectId: 'origObjectId',
      origSensorId: 'origSensorId',
      pixelBitDepth: 0,
      pixelFOVHeight: 0,
      pixelFOVWidth: 0,
      satNo: 0,
      senalt: 0,
      senlat: 0,
      senlon: 0,
      senQuat: [0],
      senQuatDot: [0],
      senx: 0,
      seny: 0,
      senz: 0,
      sequenceId: 0,
      sourceDL: 'sourceDL',
      tags: ['string'],
      topLeftStartAz: 0,
      topLeftStartEl: 0,
      topLeftStopAz: 0,
      topLeftStopEl: 0,
      transactionId: 'transactionId',
    });
  });
});
