// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../resource';

export class History extends APIResource {}

/**
 * Maintenance schedule and operational status of Sensor.
 */
export interface SensormaintenanceFull {
  /**
   * Classification marking of the data in IC/CAPCO Portion-marked format.
   */
  classificationMarking: string;

  /**
   * Indicator of whether the data is EXERCISE, REAL, SIMULATED, or TEST data:
   *
   * EXERCISE:&nbsp;Data pertaining to a government or military exercise. The data
   * may include both real and simulated data.
   *
   * REAL:&nbsp;Data collected or produced that pertains to real-world objects,
   * events, and analysis.
   *
   * SIMULATED:&nbsp;Synthetic data generated by a model to mimic real-world
   * datasets.
   *
   * TEST:&nbsp;Specific datasets used to evaluate compliance with specifications and
   * requirements, and for validating technical, functional, and performance
   * characteristics.
   */
  dataMode: 'REAL' | 'TEST' | 'SIMULATED' | 'EXERCISE';

  /**
   * The planned outage end time in ISO8601 UTC format.
   */
  endTime: string;

  /**
   * The site to which this item applies. NOTE - this site code is COLT specific and
   * may not identically correspond to other UDL site IDs.
   */
  siteCode: string;

  /**
   * Source of the data.
   */
  source: string;

  /**
   * The planned outage start time in ISO8601 UTC format.
   */
  startTime: string;

  /**
   * Unique identifier of the record, auto-generated by the system.
   */
  id?: string;

  /**
   * Description of the activity taking place during this outage.
   */
  activity?: string;

  /**
   * The name of the approver.
   */
  approver?: string;

  /**
   * The name of the changer, if applicable.
   */
  changer?: string;

  /**
   * Time the row was created in the database, auto-populated by the system.
   */
  createdAt?: string;

  /**
   * Application user who created the row in the database, auto-populated by the
   * system.
   */
  createdBy?: string;

  /**
   * The duration of the planned outage, expressed as ddd:hh:mm.
   */
  duration?: string;

  /**
   * COLT EOWID.
   */
  eowId?: string;

  /**
   * The mission capability status of the equipment (e.g. FMC, NMC, PMC, UNK, etc.).
   */
  equipStatus?: string;

  /**
   * UUID of the sensor.
   */
  idSensor?: string;

  /**
   * The sensor face(s) to which this COLT maintenance item applies, if applicable.
   */
  impactedFaces?: string;

  /**
   * The date that this item became inactive in ISO8601 UTC format.
   */
  inactiveDate?: string;

  /**
   * The internal COLT line number assigned to this item.
   */
  lineNumber?: string;

  /**
   * The Missile Defense operational capability of this maintenance item. Typical
   * values are G, Y, R, and - for non-applicable sites.
   */
  mdOpsCap?: string;

  /**
   * The Missile Warning operational capability of this maintenance item. Typical
   * values are G, Y, R, and - for non-applicable sites.
   */
  mwOpsCap?: string;

  /**
   * Originating system or organization which produced the data, if different from
   * the source. The origin may be different than the source if the source was a
   * mediating system which forwarded the data on behalf of the origin system. If
   * null, the source may be assumed to be the origin.
   */
  origin?: string;

  /**
   * The originating source network on which this record was created, auto-populated
   * by the system.
   */
  origNetwork?: string;

  /**
   * The priority of this maintenance item.
   */
  priority?: string;

  /**
   * The minimum time required to recall this activity, expressed as ddd:hh:mm.
   */
  recall?: string;

  /**
   * Release.
   */
  rel?: string;

  /**
   * Remarks concerning this outage.
   */
  remark?: string;

  /**
   * The name of the requestor.
   */
  requestor?: string;

  /**
   * The name of the resource(s) affected by this maintenance item.
   */
  resource?: string;

  /**
   * The revision number for this maintenance item.
   */
  rev?: string;

  /**
   * The Space Surveillance operational capability of this maintenance item. Typical
   * values are G, Y, R, and - for non-applicable sites.
   */
  ssOpsCap?: string;

  /**
   * Time the row was last updated in the database, auto-populated by the system.
   */
  updatedAt?: string;

  /**
   * Application user who updated the row in the database, auto-populated by the
   * system.
   */
  updatedBy?: string;
}

export declare namespace History {
  export { type SensormaintenanceFull as SensormaintenanceFull };
}
